# Generated by Django 5.2.3 on 2025-07-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("prompts", "0002_prompt_is_public_prompt_updated_at_promptrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="provider",
            field=models.CharField(default="ollama", max_length=100),
        ),
    ]
