# Generated by Django 5.2.3 on 2025-08-01 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatmessages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_flagged",
            field=models.BooleanField(default=True),
        ),
    ]
